title: WarriorHub
description: An Event Scheduler for UH Manoa
google_analytics:
show_downloads: false
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/warriorhub/warriorhub
website: https://warriorhub-gamma.vercel.app
gems:
  - jekyll-mentions
